### PR TITLE
Improve Travis testing, Uri_services

### PR DESCRIPTION
**Pull request by dsheets**
Also rolls up #71.

### CODE REVIEW

**Comment by samoht** [comment]
can we use the new service list in a unikernel (last time I checked, it looked at the service list on the filesystem at runtime, but maybe I was using the wrong functions). I'm mainly interested by the [`git://`](https://github.com/samoht/mirmin/blob/master/git/unikernel.ml#L11) service :-)

**Comment by dsheets** [comment]
I didn't end up exposing `services_full` by default so only the minimal services database is available. It is built into a module and does not require FS access. If you could be more specific about what information about the `git` service (or scheme) you'd like, I can make sure it gets into 1.9 (today).

**Comment by samoht** [comment]
the only think that I need is in the link in the previous message, eg, I need "git://" to be resolved to `{ Resolver.name = "git"; port = 9418; tls = false }` (which is not the case in the default services)

**Comment by dsheets** [comment]
Oops, I totally overlooked the embedded link. `name` and `port` are easy enough. We don't have a TLS predicate at the moment...

**Comment by avsm** [comment]
The `tls` field is added directly by the Conduit resolver since its not contained in the services file. https://github.com/mirage/ocaml-conduit/blob/master/lib/resolver_lwt_unix.ml#L36

**Pull request merged**
