### PR TITLE
Update README.md according the new package uri-re

### PR DESCRIPTION
**Pull request by dinosaure**
A minor update to show the existence (and explain it) of the new package `uri-re`.

### CODE REVIEW

**Comment by avsm** [comment]
I think it's reasonable to get rid of uri-re entirely, or if we keep it to indicate that it will be removed in a subsequent future version. 

Also, should bump to 4.0 -- the entire implementation has been rewritten, so that justifies the bump _vs_ 3.x :-)

**Comment by dinosaure** [comment]
Let's keep a chance for user to see any diff between the old version and the new version - I will make an issue to keep in our mind that `uri-re` should be deprecated then :+1:.

**Comment by dinosaure** [comment]
> I think it's reasonable to get rid of uri-re entirely, or if we keep it to indicate that it will be removed in a subsequent future version.

The README.md was updated and an issue was created about that (see #150).

> Also, should bump to 4.0 -- the entire implementation has been rewritten, so that justifies the bump vs 3.x :-)

Fixed according ocaml/opam-repository#17411

**Comment by avsm** [comment]
Many thanks!

**Pull request merged**
