### PR TITLE
also set wrapped to be false in jbuilder

### PR DESCRIPTION
**Pull request by avsm**
This will rerelease 1.9.4 as it is more compatible with the older
layout. I've put a note into CHANGES about where to expect breakage.

### CODE REVIEW

**Comment by dsheets** [comment]
Aughhh... I just merged #97 which should go into 1.10.0. :-/ Sorry about that.

**Comment by avsm** [comment]
@dsheets that;s ok, i can branch for this minor change -- sorry about the release shenanighans, as the revdep testing in opam-repository showed up the failures. I'll see about setting that up on more of the mirage repositories...

**Comment by avsm** [comment]
release attempt number 2 at https://github.com/ocaml/opam-repository/pull/9378, based off this branch. will merge when the revdeps check out

**Comment by dsheets** [comment]
https://github.com/mirage/ocaml-uri/tree/v1.9.4 seems to contain `with_uri` but the tarball released to opam does not. Somehow, the tag does not match the tarball being released. I guess custom release tarball not matching tag is a failure mode of using topkg somehow?

**Pull request merged**
