### PR TITLE
Prepare v4.1.0

### PR DESCRIPTION
**Pull request by TheLortex**
Minor release to fix cross-compilation issues

### CODE REVIEW

**Review by dinosaure — APPROVED** [review]

**Comment by dinosaure** [comment]
May be, with the deprecation, we need to bump `4.1.0`, I'm not sure (/cc @avsm).

**Comment by avsm** [comment]
good catch @dinosaure -- yes please don't deprecate a package in a point release. Also, would it be possible to note in the CHANGES why its deprecated and what the person using it should do about it?

**Comment by TheLortex** [comment]
Thank you, I updated the version and the message to add more info.

**Comment by dinosaure** [comment]
The CI is ok (according to OCaml CI), ready to merge.

**Pull request merged**
