### PR TITLE
Fix CI: Update system package manager before installing packages

### PR DESCRIPTION
**Pull request by kit-ty-kate**
See #111

### CODE REVIEW

**Comment by jpdeplaix** [comment]
Ping @vbmithr

**Comment by hannesm** [comment]
the travis build claims there's no fedora26 OCaml-4.03.0 container, maybe just remove it from .travis.yml?

travis output https://api.travis-ci.org/v3/job/330396018/log.txt
```
travis_1.10s$ bash ./.travis-docker.sh
prepare.ci
Sending build context to Docker daemon  1.257MB
Step 1/6 : FROM ocaml/opam:fedora-26_ocaml-4.03.0
manifest for ocaml/opam:fedora-26_ocaml-4.03.0 not found
Dockerfile:
FROM ocaml/opam:fedora-26_ocaml-4.03.0
WORKDIR /home/opam/opam-repository
RUN git pull origin master
RUN opam update -u -y
VOLUME /repo
WORKDIR /repo
env.list:
PACKAGE=uri
EXTRA_REMOTES=
PINS=
INSTALL=
DEPOPTS=
TESTS=
REVDEPS=cohttp git github irmin sociaml-facebook-api sociaml-oauth-client sociaml-tumblr-api spotify-web-api syndic
EXTRA_DEPS=
PRE_INSTALL_HOOK=
POST_INSTALL_HOOK=OPAMYES=true opam depext -ui react ssl lwt
Command:
docker run --env-file=env.list -v /home/travis/build/mirage/ocaml-uri:/repo local-build ci-opam
Unable to find image 'local-build:latest' locally
docker: Error response from daemon: pull access denied for local-build, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

**Comment by jpdeplaix** [comment]
Looks like Fedora 26 is not available but Fedora 25 is.
The change comes from this commit (cc @avsm): https://github.com/mirage/ocaml-uri/commit/220e5ae4a4406d48b262725880bfe70b75543188
I've changed it back so it can pass the CI.

**Comment by avsm** [comment]
not an issue any more i think....

**Pull request closed without merging**
